version: "3.8"

services:
    ui:
        build: ./ui #TODO 
        ports:
            - 80:80
        deploy:
            replicas: 10
            placement:
                max_replicas_per_node: 2
            update_config:
                parallelism: 2
                order: start-first
            rollback_config:
                parallelism: 2
                order: start-first
        networks:
            - ui-recipe-manager
            - ui-mass-halls
  
    recipe-manager-service:
        build: ./recipe-manager-service
        deploy:
            replicas: 2
            placement:
                max_replicas_per_node: 1
            update_config:
                order: start-first
            rollback_config:
                order: start-first
        networks:
            - ui-recipe-manager
            - recipe-manager-db

    mass-halls-manager-service:
        build: ./mass-halls-manager-service
        deploy:
            replicas: 6
            placement:
                max_replicas_per_node: 2
            update_config:
                order: start-first
            rollback_config:
                order: start-first
        networks:
            - ui-mass-halls
            - mass-halls-manager-db

    db:
        image: postgres:12
        environment:
            POSTGRES_DB: recipe #TODO
            POSTGRES_USER: admin #TODO
            POSTGRES_PASSWORD: admin #TODO
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
        volumes:
            - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql #TODO
            - db-volume:/var/lib/postgresql/data
        networks:
            - recipe-manager-db
            - mass-halls-manager-db

volumes:
    db-volume:

networks:
    ui-recipe-manager:
    ui-mass-halls:
    recipe-manager-db:
    mass-halls-manager-db:
