name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Frontend
      run: sudo docker build ./ui -t ${{ secrets.DOCKER_HUB_USERNAME }}/ui
    - name: Build MassHalls
      run: sudo docker build ./recipe-manager-service -t ${{ secrets.DOCKER_HUB_USERNAME }}/recipe-manager-service
    - name: Build Recipe
      run: sudo docker build ./mass-halls-manager-service -t ${{ secrets.DOCKER_HUB_USERNAME }}/mass-halls-manager-service 
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Publish docker image
      run: |-
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mass-halls-manager-service
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/recipe-manager-service
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ui
  
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:    
      - name: Deploy the stack
        run: |-
          sudo docker stack deploy -c docker-compose-portainer.yml PortainerStack
          sudo docker stack deploy -c docker-compose.yml WarDineStack
#     - name: Webhook POST Action to Portainer
      # You may pin to the exact commit or the version.
      # uses: muinmomin/webhook-action@7c067ef19e5de3aca7aebda32628f1d08d06bf89
#       uses: muinmomin/webhook-action@v1.0.0
#       with:
#         url: http://localhost:9000/api/webhooks/2d7381a6-08d4-4ead-bd68-45114d73cb64
