name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Frontend
      run: sudo docker build ./ui -t ui
    - name: Build MassHalls
      run: sudo docker build ./recipe-manager-service -t recipe-manager-service
    - name: Build Recipe
      run: sudo docker build ./mass-halls-manager-service -t mass-halls-manager-service 
